### ISSUE TITLE
Problem of plotMotifHeatmaps function - missing motif logos

### ISSUE THREAD

**Issue by leezx** [fmicompbio/monaLisa#78] opened 2024-07-09 22:00 UTC
I used the following code to draw heatmap, but some motif logos were missing.
```
options(repr.plot.width=9, repr.plot.height=15)
plotMotifHeatmaps(x = D2_D4_close_se[pv$tf[1:50],],
                  which.plots = c("log2enr"), # , "negLog10Padj"
                  width = 1.5, maxEnr = NULL, maxSig = NULL,
                  cluster = TRUE,
                  show_dendrogram = FALSE, show_motif_GC = FALSE,
                  show_seqlogo = TRUE, width.seqlogo = 1, use_raster = TRUE
                 )
```
![Picture1](https://github.com/fmicompbio/monaLisa/assets/13306295/81de87ab-1296-400c-a2bc-d781a799b71d)

However, when I used the internal code to draw motif logos, none was missing. I guess there must be some problems in the further integration of heatmap.
```
width.seqlogo = 1
pfms <- rowData(x)$motif.pfm
maxwidth <- max(vapply(TFBSTools::Matrix(pfms), ncol, 
    0L))
grobL <- lapply(pfms, seqLogoGrob, xmax = maxwidth, xjust = "center")
hmSeqlogo <- HeatmapAnnotation(logo = annoSeqlogo(grobL = grobL, 
    which = "row", space = unit(0.5, "mm"), width = unit(width.seqlogo, 
        "inch")), show_legend = FALSE, show_annotation_name = FALSE, 
    which = "row")
draw(hmSeqlogo)
```
![Picture2](https://github.com/fmicompbio/monaLisa/assets/13306295/710ea248-3115-4fa6-9104-13e0a94adf51)

Can you fix this issue?

**Comment by leezx** [comment] 2024-07-09 22:01
packageVersion("monaLisa")
[1] '1.4.0'

packageVersion("ComplexHeatmap")
[1] '2.14.0'

**Comment by mbstadler** [comment] 2024-07-10 07:43
@leezx I cannot reproduce your issue with the current release version of `monaLisa` (version 1.10.0) and the built-in example data (e.g. running `example("plotMotifHeatmaps")`).

Could you try updating your installation of R/Bioconductor to the latest version, and try again.

If that still fails, could you provide a reproducible example?

**Comment by mbstadler** [comment] 2024-07-12 06:07
Are you observing this problem within RStudio or a similar IDE? The reason why I am asking is that I have seen some plots to be only visualized partially within and IDE, but if the plot is writting to a file (e.g. a .png or a .pdf), it will show completely.

Maybe that would be also something that you could try.

**Comment by mbstadler** [comment] 2024-07-16 07:07
@leezx I am closing the issue for the moment. Feel free to reopen it if you have any further questions.

**Closed as completed by mbstadler** 2024-07-16 07:07 UTC
