### ISSUE TITLE
Error - bin() -  ....  'breaks' are not unique

### ISSUE THREAD

**Issue by matteozoia4** [fmicompbio/monaLisa#67] opened 2023-08-15 09:18 UTC
Dear monaLisa providers,

**I am working with this .bed file (here in .csv) :**
[file.csv](https://github.com/fmicompbio/monaLisa/files/12343924/file.csv)

**When running bin() :**
```
bins <- bin(x = lmrsel$score, binmode = "equalN", nElement = 800, 
            minAbsX = 0.3)
table(bins)
```

**I get this error :** 
```
Error in cut.default(x, breaks = breaks, include.lowest = TRUE, ...) : 
  'breaks' are not unique
```

_How could I fix this error?_
_My best regards and thank you for your help!_

_MZ_

**Session(Info)**
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] JASPAR2022_0.99.7                  BiocFileCache_2.6.1               
 [3] dbplyr_2.3.3                       BiocStyle_2.26.0                  
 [5] dplyr_1.1.2                        circlize_0.4.15                   
 [7] ComplexHeatmap_2.14.0              BSgenome.Mmusculus.UCSC.mm10_1.4.3
 [9] BSgenome_1.66.3                    rtracklayer_1.58.0                
[11] Biostrings_2.66.0                  XVector_0.38.0                    
[13] TFBSTools_1.36.0                   JASPAR2020_0.99.10                
[15] SummarizedExperiment_1.28.0        Biobase_2.58.0                    
[17] MatrixGenerics_1.10.0              matrixStats_1.0.0                 
[19] GenomicRanges_1.50.2               GenomeInfoDb_1.34.9               
[21] IRanges_2.32.0                     S4Vectors_0.36.2                  
[23] BiocGenerics_0.44.0                monaLisa_1.4.0                    
[25] MatrixModels_0.5-1                 BiocManager_1.30.22               

loaded via a namespace (and not attached):
  [1] vioplot_0.4.0               colorspace_2.1-0            rjson_0.2.21               
  [4] GlobalOptions_0.1.2         clue_0.3-64                 rstudioapi_0.15.0          
  [7] bit64_4.0.5                 AnnotationDbi_1.60.2        fansi_1.0.4                
 [10] codetools_0.2-19            splines_4.2.1               R.methodsS3_1.8.2          
 [13] doParallel_1.0.17           cachem_1.0.8                knitr_1.43                 
 [16] Rsamtools_2.14.0            seqLogo_1.64.0              annotate_1.76.0            
 [19] cluster_2.1.4               GO.db_3.16.0                png_0.1-8                  
 [22] R.oo_1.25.0                 readr_2.1.4                 compiler_4.2.1             
 [25] httr_1.4.6                  Matrix_1.5-4.1              fastmap_1.1.1              
 [28] cli_3.6.1                   htmltools_0.5.6             tools_4.2.1                
 [31] gtable_0.3.3                glue_1.6.2                  TFMPvalue_0.0.9            
 [34] GenomeInfoDbData_1.2.9      reshape2_1.4.4              rappdirs_0.3.3             
 [37] Rcpp_1.0.11                 vctrs_0.6.3                 iterators_1.0.14           
 [40] xfun_0.40                   CNEr_1.34.0                 stringr_1.5.0              
 [43] lifecycle_1.0.3             restfulr_0.0.15             poweRlaw_0.70.6            
 [46] gtools_3.9.4                XML_3.99-0.14               zlibbioc_1.44.0            
 [49] zoo_1.8-12                  scales_1.2.1                hms_1.1.3                  
 [52] parallel_4.2.1              RColorBrewer_1.1-3          curl_5.0.1                 
 [55] yaml_2.3.7                  memoise_2.0.1               ggplot2_3.4.3              
 [58] stabs_0.6-4                 stringi_1.7.12              RSQLite_2.3.1              
 [61] BiocIO_1.8.0                foreach_1.5.2               filelock_1.0.2             
 [64] caTools_1.18.2              BiocParallel_1.32.6         shape_1.4.6                
 [67] rlang_1.1.1                 pkgconfig_2.0.3             bitops_1.0-7               
 [70] evaluate_0.21               pracma_2.4.2                lattice_0.21-8             
 [73] purrr_1.0.2                 GenomicAlignments_1.34.1    patchwork_1.1.3            
 [76] bit_4.0.5                   tidyselect_1.2.0            plyr_1.8.8                 
 [79] magrittr_2.0.3              R6_2.5.1                    generics_0.1.3             
 [82] DelayedArray_0.24.0         DBI_1.1.3                   sm_2.2-5.7.1               
 [85] pillar_1.9.0                withr_2.5.0                 survival_3.5-5             
 [88] KEGGREST_1.38.0             RCurl_1.98-1.12             tibble_3.2.1               
 [91] crayon_1.5.2                utf8_1.2.3                  rmarkdown_2.24             
 [94] tzdb_0.4.0                  GetoptLong_1.0.5            blob_1.2.4                 
 [97] digest_0.6.33               xtable_1.8-4                tidyr_1.3.0                
[100] R.utils_2.12.2              munsell_0.5.0               glmnet_4.1-7               
[103] DirichletMultinomial_1.40.0

**Comment by matteozoia4** [comment] 2023-08-16 12:35
Given the regions vary in size I settled up that way the code for bin()
```
bins <- bin(x = lmrsel$score, binmode = "breaks", nElement = 250776, 
            minAbsX = 0.3, breaks=c(0,5,10,15,20,25,31))
table(bins)
```
Is this correct ?

**Comment by mbstadler** [comment] 2023-08-21 05:52
Hello @matteozoia4 

I can reproduce your issue, and here is the reason why `monaLisa::bin` fails:

You are working with 656,353 regions, and your call:
`bins <- bin(x = lmrsel$score, binmode = "equalN", nElement = 800,  minAbsX = 0.3)`

asks to make bin containing 800 of these each, which would result in ~800 bins (ignoring
for the moment that use use `minAbsX` which will reduce that number.

Now `bins` calls `cut` from base-R internally, which will require that each bin
has unique breaks that define the score interval for each bin. This fails because
you have many more than 800 values with identical scores, so that neighboring
bins would have identical lower/upper breaks.

For example, you have:
```
> sum(lmrsel$score == min(lmrsel$score))
[1] 185532
> min(lmrsel$score)
[1] 0.816622
```

over 185,000 values that all have identical scores of 0.816622.

You have several options to solve this (possibly a combination thereof):

- don't use all your regions (for example, take a random subset of them)
- enlarge the bins (use a larger value of `nElement`)
- use another `binmode` (both `equalWidth` and `breaks` would work here, for example: `bins <- bin(x = lmrsel$score, binmode = "equalWidth", nBins = 10)`, or the example you gave above, in which however `nElement` will be ignored and should maybe not be given to avoid confusion)

A final remark to `minAbsX = 0.3`: This value will not have any effect, since all your scores are > 0.8. `minAbsX` is used to group small values around zero, which is not the case for your scores.

I will close the issue for now - please reopen it if you have any further questions.

**Closed as completed** 2023-08-21 06:03 UTC
